#%RAML 1.0
title: Blockchain APIs
version: v1
baseUri: /api/{version}
mediaType: application/json


/mine:
  description: This should be used to add one more block
  post:
    body:
      application/x-www-form-urlencoded:
      application/json:
        properties:
          data: 
            description: This should be the data to enter in the block
            required: true
            type: string
          extraData: 
            description: This should be the extraData only visible to adding node
            required: true
            type: string
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
                message: string
      
      500:
        body:
          application/json:
            type: object
            properties:
                error: string

/addpeer:
  description: This should be used to add one peer
  post:
    body:
      application/x-www-form-urlencoded:
      application/json:
        properties:
          peer: 
            description: This should be the ws link of a running node
            required: true
            type: string
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
                message: string      
      500:
        body:
          application/json:
            type: object
            properties:
                error: string



          
                